/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mapas;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.color.ColorSpace;
import static java.lang.System.console;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Practica IA1
 */
public class Ventana extends javax.swing.JFrame {

    
    private JButton matrizBotones[][];   // matriz de botones para mostrar en la UI
    private int mapa[][];               //  matriz inicial donde se ralizara la busqueda
    private int res[][];                // matriz para guardar resultados parciales
    private String resCad[][];          // matriz con los colores que se pintara el mapa
    private GeneradorMatriz gm;         // clase que tiene el algoritmo de busqueda por profundidad    
    private int tam;                    // tamanio de la matriz que se quiere generar
    private String color;               // variable para guardar el color a pintar

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    
    public void iniciarMatriz(int m[][]) {
        for (int f = 0; f < tam; f++) {
            for (int c = 0; c < tam; c++) {
                mapa[f][c] = 0;
            }
        }
    }

    public void construirMatrizBotones(int m[][]) {
        resCad = new String[this.tam][this.tam];
        //strArray[i] = String.valueOf(intArray[i]);
        for (int f = 0; f < tam; f++) {
            for (int c = 0; c < tam; c++) {
                if (m[f][c] == 1) {
                    color = "magenta";
                }
                if (m[f][c] == 2) {
                    color = "cyan";
                }
                if (m[f][c] == 3) {
                    color = "green";
                }
                if (m[f][c] == 4) {
                    color = "orange";
                }
                //resCad[f][c] = String.valueOf(m[f][c]);
                resCad[f][c] = color;
            }
        }
        panel.setLayout(new GridLayout(tam, tam));
        matrizBotones = new JButton[tam][tam];
        for (int f = 0; f < tam; f++) {
            for (int c = 0; c < tam; c++) {
                JButton nuevoBoton = new JButton(resCad[f][c]);
                String colorApintar = resCad[f][c];
                Color colorbg;
                try {
                    Field field = Class.forName("java.awt.Color").getField(colorApintar);
                    colorbg = (Color) field.get(null);
                } catch (Exception e) {
                    colorbg = null; // Not defined
                }
                nuevoBoton.setBackground(colorbg);
                matrizBotones[f][c] = nuevoBoton;
                //matrizBotones[f][c] = new JButton(resCad[f][c]);
                panel.add(matrizBotones[f][c]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        cbxTamanio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(null);
        jScrollPane1.setViewportView(panel);

        cbxTamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2x2", "3x3", "4x4", "5x5", "6x6", "7x7" }));

        jLabel1.setText("Tamaño Mapa");

        jButton1.setText("Pintar Mapa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cbxTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lb2)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //char tamSeleccionado = (cbxTamanio.getSelectedItem().toString()).charAt(0);
        int tamSelec = Character.getNumericValue((cbxTamanio.getSelectedItem().toString()).charAt(0));
        this.tam = tamSelec;
        lb2.setVisible(false);
        lb2.setText("" + tamSelec);
        jButton1.setEnabled(false);
        
        cbxTamanio.setEnabled(false);

        mapa = new int[tam][tam];
        iniciarMatriz(mapa);
        gm = new GeneradorMatriz(mapa, 4);
        gm.mostrar(mapa);
        res = new int[tam][tam];
        res = gm.profundidadDFS();
        //transformarMatriz();
        construirMatrizBotones(res);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTamanio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
